import uuid
from django.db import models


class InterviewSession(models.Model):
    """Represents a single end-to-end AI Interview preparation session."""
    
    class Status(models.TextChoices):
        CREATED = 'CREATED', 'Created'
        UPLOADING = 'UPLOADING', 'Uploading'
        ANALYZING = 'ANALYZING', 'Analyzing'
        COMPLETED = 'COMPLETED', 'Completed'
        FAILED = 'FAILED', 'Failed'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session_number = models.PositiveIntegerField(editable=False, null=True, blank=True)
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.CREATED
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.session_number:
            # Safely calculate next sequential number
            max_num = InterviewSession.objects.aggregate(models.Max('session_number'))['session_number__max']
            self.session_number = (max_num or 0) + 1
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Session #{self.session_number or self.id} ({self.status})"


class ResumeData(models.Model):
    """Parsed and analyzed resume data associated with an interview session."""
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.OneToOneField(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name='resume'
    )
    file_path = models.CharField(max_length=500, blank=True, null=True)
    raw_text = models.TextField()
    skills = models.JSONField(default=list, blank=True)
    experience = models.JSONField(default=list, blank=True)
    projects = models.JSONField(default=list, blank=True)
    technologies = models.JSONField(default=list, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Resume for Session {self.session.id}"


class JobDescriptionData(models.Model):
    """Submitted and analyzed job description data."""
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.OneToOneField(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name='job_description'
    )
    raw_text = models.TextField()
    required_skills = models.JSONField(default=list, blank=True)
    preferred_skills = models.JSONField(default=list, blank=True)
    responsibilities = models.JSONField(default=list, blank=True)
    experience_requirements = models.JSONField(default=list, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"JD for Session {self.session.id}"


class GapAnalysisResult(models.Model):
    """Result of the Gap Analysis comparing Resume vs JD."""
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.OneToOneField(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name='gap_analysis'
    )
    matching_skills = models.JSONField(default=list, blank=True)
    missing_skills = models.JSONField(default=list, blank=True)
    strengths = models.JSONField(default=list, blank=True)
    readiness_score = models.FloatField(default=0.0)
    summary = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Gap Analysis for Session {self.session.id} (Score: {self.readiness_score})"


class InterviewQuestionsResult(models.Model):
    """Questions generated by the question generator agent."""
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.OneToOneField(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name='questions'
    )
    easy_questions = models.JSONField(default=list, blank=True)
    medium_questions = models.JSONField(default=list, blank=True)
    hard_questions = models.JSONField(default=list, blank=True)
    behavioral_questions = models.JSONField(default=list, blank=True)
    company_questions = models.JSONField(default=list, blank=True)
    followup_questions = models.JSONField(default=list, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Questions for Session {self.session.id}"


class LearningRoadmapResult(models.Model):
    """Roadmap plan generated by the roadmap generator agent."""
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.OneToOneField(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name='roadmap'
    )
    study_plan = models.JSONField(default=list, blank=True)
    prioritized_skills = models.JSONField(default=list, blank=True)
    learning_sequence = models.JSONField(default=list, blank=True)
    summary = models.TextField(blank=True, null=True)
    estimated_days = models.IntegerField(default=7)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Roadmap for Session {self.session.id}"
