# Generated by Django 5.2.14 on 2026-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='session_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
